[package]
name = "bevy_asset_ldtk"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy       = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }

[lints]
workspace = true
